#pragma once

#include "core/smart_pointer.h"
#include "rhi/rhi_forward.h"
#include "rhi/texture.h"
#include "render/scene_render_pass.h"
#include "render/util/volatile_descriptor.h"

struct DenoiserPluginInput
{
	uint32                 imageWidth;
	uint32                 imageHeight;
	ShaderResourceView*    sceneColorSRV;
	ShaderResourceView*    gbuffer0SRV;
	ShaderResourceView*    gbuffer1SRV;
};

class DenoiserPluginPass final : public SceneRenderPass
{
public:
	void initialize(RenderDevice* inDevice);

	bool isAvailable() const;

	void blitTextures(RenderCommandList* commandList, uint32 swapchainIndex, const DenoiserPluginInput& passInput);

	/// <summary>
	/// Execute denoiser with input images that were generated by blitTextures().
	/// </summary>
	/// <param name="commandList"></param>
	/// <param name="dstWidth"></param>
	/// <param name="dstHeight"></param>
	/// <param name="dst"></param>
	void executeDenoiser(RenderCommandList* commandList, uint32 dstWidth, uint32 dstHeight, Texture* dst);

private:
	void resizeTextures(uint32 newWidth, uint32 newHeight);

private:
	RenderDevice* device = nullptr;

	UniquePtr<ComputePipelineState> blitPipelineState;
	VolatileDescriptorHelper blitPassDescriptor;

	UniquePtr<Texture> colorTexture;
	UniquePtr<Texture> albedoTexture;
	UniquePtr<Texture> normalTexture;
	UniquePtr<Texture> denoisedTexture;

	UniquePtr<UnorderedAccessView> colorUAV;
	UniquePtr<UnorderedAccessView> albedoUAV;
	UniquePtr<UnorderedAccessView> normalUAV;

	SharedPtr<Texture::ReadbackHandle> colorReadbackHandle;
	SharedPtr<Texture::ReadbackHandle> albedoReadbackHandle;
	SharedPtr<Texture::ReadbackHandle> normalReadbackHandle;
};
